# Generated by Django 2.1.2 on 2018-10-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.IntegerField()),
                ('especificacion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion1', models.CharField(max_length=200)),
                ('opcion2', models.CharField(max_length=200)),
                ('opcion3', models.CharField(max_length=200)),
                ('opcion4', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appslack.Cliente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appslack.Menu'),
        ),
    ]
